### ISSUE TITLE
Removing old Timer test fails

### ISSUE THREAD

**Issue by valerieshoskes** [valerieshoskes/codedayissues#3]
When running the Capybara test suite, the test for removing old timers fails with:

And all old timers are removed
      unable to locate element: #<Watir::Anchor: located: false; {:text=>"STOP", :tag_name=>"a"}> (Watir::Exception::UnknownObjectException)
      ./features/support/pages/timer_page.rb:52:in `remove_all_timers'
      ./features/step_definitions/timer_steps.rb:2:in `/^all old timers are removed$/'
      features/timer_page.feature:5:in `And all old timers are removed'

I need to determine whether this is an issue with the source code or the test suite, and react accordingly.

**Comment by valerieshoskes** [comment]
This was actually in the cucumber suite, and has been fixed there.
