### ISSUE TITLE
Cucumber suite: Test for removing old timers fails

### ISSUE THREAD

**Issue by valerieshoskes** [valerieshoskes/codedayissues#5]
The test for removing old timers fails with 

And all old timers are removed
      unable to locate element: #<Watir::Anchor: located: false; {:text=>"STOP", :tag_name=>"a"}> (Watir::Exception::UnknownObjectException)
      ./features/support/pages/timer_page.rb:52:in `remove_all_timers'
      ./features/step_definitions/timer_steps.rb:2:in `/^all old timers are removed$/'
      features/timer_page.feature:5:in `And all old timers are removed'

As this also fails in Capybara, I suspect this is an issue with the source code, but this will need to be confirmed via exploratory testing and checking the code base. If it is an issue with the testing suite, this will need to be resolved.

**Comment by valerieshoskes** [comment]
This was found to be erroring out in the testing suite. I fixed the issue by having the cucumber tests look for elements being present rather than visible.
